[build]
  command = "npm install"
  functions = "netlify/functions" # مسیر درست فانکشن‌ها
  publish = "."


[build.environment]
  NODE_VERSION = "18" # نسخه Node.js برای سازگاری با googleapis

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200