[build]
     command = "npm install"
     functions = "netlify/functions"
     publish = "."
   [build.environment]
     NODE_VERSION = "20"
   
   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
   
   [[redirects]]
     from = "/form.html"
     to = "/.netlify/functions/check-auth"
     status = 200
     force = true
     conditions = {Role = ["authenticated"]}